ECommerceCase.WebClient/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ECommerceCase.WebClient.Extensions;
using ECommerceCase.WebClient.Services.Interfaces;
using ECommerceCase.WebClient.ViewModels.Auth;
using ErtisAuth.Core.Models.Users;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace ECommerceCase.WebClient.Controllers
{
	public class AuthController : BaseController
	{
		#region Services

		private readonly IAuthService authService;
		private readonly ILogger<AuthController> _logger;
		
		#endregion

		#region Properties

		private string AdministratorToken { get; }

		#endregion
		
		#region Constructors

		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="authService"></param>
		/// <param name="configuration"></param>
		/// <param name="logger"></param>
		public AuthController(IAuthService authService, IConfiguration configuration, ILogger<AuthController> logger) : base(authService)
		{
			this.authService = authService;
			this._logger = logger;

			this.AdministratorToken = configuration.GetSection("ErtisAuth")["AdministratorToken"];
		}

		#endregion

		#region Login & Logout

		[Route("login")]
        public IActionResult Login()
		{
			if (this.IsLoggedIn)
			{
				return this.RedirectToAction("Index", "Home");
			}
			
			var referer = this.Request.GetReferer();
			if (referer != null)
			{
				this.ViewBag.ReturnUrl = referer;
			}

			LoginViewModel viewModel = new LoginViewModel
			{
				IsHealthy = this.authService.HealthCheck().IsSuccess
			};
			
            return this.View(viewModel);
        }

        [HttpPost]
        [Route("login")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
			if (this.ModelState.IsValid)
            {
                var getTokenResult = await this.authService.LoginAsync(model.Username, model.Password);
				if (getTokenResult.IsSuccess)
				{
					// Who am i?
					var meResult = await this.authService.MeAsync(getTokenResult.Data.AccessToken);
					if (meResult.IsSuccess)
					{
						var claims = new List<Claim>
						{
							new Claim("id", meResult.Data.Id),
							new Claim("username", meResult.Data.Username ?? string.Empty),
							new Claim("email", meResult.Data.EmailAddress ?? string.Empty),
							new Claim("firstName", meResult.Data.FirstName ?? string.Empty),
							new Claim("lastName", meResult.Data.LastName ?? string.Empty),
							new Claim("role", meResult.Data.Role ?? string.Empty),
							new Claim("access_token", getTokenResult.Data.AccessToken),
							new Claim("refresh_token", getTokenResult.Data.RefreshToken)
						};

						var authProperties = new AuthenticationProperties
						{
							IsPersistent = true,
							AllowRefresh = true
						};

						var authTokens = new List<AuthenticationToken>
						{
							new AuthenticationToken
							{
								Name = "AccessToken",
								Value = getTokenResult.Data.AccessToken
							},
							new AuthenticationToken
							{
								Name = "RefreshToken",
								Value = getTokenResult.Data.RefreshToken
							}
						};

						authProperties.StoreTokens(authTokens);

						await this.HttpContext.SignInAsync(new ClaimsPrincipal(new ClaimsIdentity(claims, "Cookies", "id", "role")), authProperties);

						if (model.ReturnUrlAfterLogin != null && new Uri(model.ReturnUrlAfterLogin).IsValidUrl())
						{
							return this.Redirect(model.ReturnUrlAfterLogin);	
						}
						else
						{
							return this.RedirectToAction("Index", "Home");	
						}
					}
					else
					{
						_logger.Log(LogLevel.Information, meResult.Message);
						this.ModelState.AddModelError(string.Empty, meResult.Message);
						return this.View(model);
					}
				}
                else
                {
					_logger.Log(LogLevel.Information, getTokenResult.Message);
					this.ModelState.AddModelError(string.Empty, getTokenResult.Message);
					return this.View(model);
                }
            }

            return this.View(model);
		}

		[Route("logout")]
        public async Task<IActionResult> Logout(string returnUrl)
        {
			var accessTokenClaim = this.User.Claims.FirstOrDefault(x => x.Type == "access_token");
			if (accessTokenClaim != null)
			{
				await this.authService.RevokeTokenAsync(accessTokenClaim.Value);	
			}
			
			var refreshTokenClaim = this.User.Claims.FirstOrDefault(x => x.Type == "refresh_token");
			if (refreshTokenClaim != null)
			{
				await this.authService.RevokeTokenAsync(refreshTokenClaim.Value);	
			}
			
			await this.HttpContext.SignOutAsync();
			if (string.IsNullOrEmpty(returnUrl))
				return this.Redirect("/");
			else
				return this.Redirect(returnUrl);
        }

		#endregion
		
		#region Register

		[Route("register")]
        public IActionResult Register()
        {
			if (this.IsLoggedIn)
			{
				return this.RedirectToAction("Index", "Home");
			}
			
            return this.View();
        }
		
        [HttpPost]
        [Route("register")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterViewModel model)
		{
			string firstName;
			string lastName;
			
			var fullNameWords = model.FirstName.Split(" ");
			if (fullNameWords.Length > 1)
			{
				firstName = string.Join(" ", fullNameWords.Take(fullNameWords.Length - 1));
				lastName = fullNameWords.LastOrDefault().Trim();
			}
			else
			{
				firstName = model.FirstName;
				lastName = string.Empty;
			}
			
			if (this.ModelState.IsValid)
            {
				if (model.PasswordFirst == null || model.PasswordSecond == null || model.PasswordFirst.Trim() != model.PasswordSecond.Trim())
				{
					this.ModelState.AddModelError(string.Empty, "Passwords does not matched!");
					return this.View(model);
				}
				
                var registerResponse = await this.authService.RegisterAsync(new User
				{
					Username = model.Email,
					EmailAddress = model.Email,
					FirstName = firstName,
					LastName = lastName,
					Role = "enduser",
					Status = "active"
				}, model.PasswordFirst);
				
                if (registerResponse.IsSuccess)
				{
					return await this.Login(new LoginViewModel { Username = model.Email, Password = model.PasswordFirst });
                }
                else
                {
					this._logger.Log(LogLevel.Error, registerResponse.Message);
					this.ModelState.AddModelError(string.Empty, registerResponse.Message);
					return this.View(model);
                }
            }
            else
            {
                return this.View(model);
            }
		}

		#endregion
	}
}

ECommerceCase.WebClient/ViewComponents/NavigationMenuViewComponent.cs
using System.Threading.Tasks;
using ECommerceCase.WebClient.Services.Interfaces;
using ECommerceCase.WebClient.ViewModels.Menu;
using Microsoft.AspNetCore.Mvc;

namespace ECommerceCase.WebClient.ViewComponents
{
	public class NavigationMenuViewComponent : ViewComponent
	{
		#region Services

		private readonly IMenuService menuService;

		#endregion
		
		#region Constructors

		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="menuService"></param>
		public NavigationMenuViewComponent(IMenuService menuService)
		{
			this.menuService = menuService;
		}

		#endregion
		
		#region Methods

		public async Task<IViewComponentResult> InvokeAsync()
		{
			NavigationMenuViewModel viewModel = new NavigationMenuViewModel();
			var getMenuResponse = await menuService.GetNavigationMenuAsync();
			if (getMenuResponse.IsSuccess)
			{
				viewModel.Menu = getMenuResponse.Data;
			}
			else
			{
				viewModel.ModelStateErrorMessage = getMenuResponse.Message;
			}
			
			return this.View(viewModel);
		}
		
		#endregion
	}
}

ECommerceCase.WebClient/ViewComponents/ShoppingCartButtonViewComponent.cs
using System.Linq;
using System.Threading.Tasks;
using ECommerceCase.WebClient.Services.Interfaces;
using ECommerceCase.WebClient.ViewModels.ShoppingCart;
using Microsoft.AspNetCore.Mvc;

namespace ECommerceCase.WebClient.ViewComponents
{
	public class ShoppingCartButtonViewComponent : ViewComponent
	{
		#region Services

		private readonly IShoppingService shoppingService;

		#endregion
		
		#region Constructors

		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="shoppingService"></param>
		public ShoppingCartButtonViewComponent(IShoppingService shoppingService)
		{
			this.shoppingService = shoppingService;
		}

		#endregion
		
		#region Methods

		public async Task<IViewComponentResult> InvokeAsync()
		{
			ShoppingCartButtonViewModel viewModel = new ShoppingCartButtonViewModel();

			var userId = this.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "id")?.Value;
			var getShoppingCartItemsResponse = await this.shoppingService.GetShoppingCartItemsAsync(userId);
			if (getShoppingCartItemsResponse.IsSuccess)
			{
				viewModel.ShoppingCartItems = getShoppingCartItemsResponse.Data.ToList();
			}
			
			return this.View(viewModel);
		}
		
		#endregion
	}
}

ECommerceCase.WebClient/Views/Shared/_Footer.cshtml
<footer class="w3-padding-64 w3-light-grey w3-small w3-center" id="footer">
	<div class="w3-row-padding">

	</div>
</footer>

ECommerceCase.WebClient/Views/Shared/_Header.cshtml
@using ECommerceCase.WebClient.Models.Auth

@{
	UserModel LoggedInUser = null;
	@if (User.Identity.IsAuthenticated)
	{
		LoggedInUser = new UserModel
		{
			Id = User.Claims.FirstOrDefault(p => p.Type == "id")?.Value,
			Username = User.Claims.FirstOrDefault(p => p.Type == "username")?.Value,
			Email = User.Claims.FirstOrDefault(p => p.Type == "email")?.Value,
			FirstName = User.Claims.FirstOrDefault(p => p.Type == "firstName")?.Value,
			LastName = User.Claims.FirstOrDefault(p => p.Type == "lastName")?.Value
		};
	}
}

<header class="w3-container w3-xlarge" style="margin-top: 30px; margin-bottom: 20px;">
	<p class="w3-left">ECommerceCase</p>
	
	<div class="w3-right">
		<div style="display: inline-block;">
			@await Component.InvokeAsync("ShoppingCartButton")	
        </div>
		
		<div style="display: inline-block;">
			@if (User.Identity.IsAuthenticated)
			{
				<i class="fa fa-user"><span style="margin-left: 10px; font-family: 'Roboto', sans-serif; font-size: 18px;">@LoggedInUser.FullName</span></i>

				<a class="icon icon-profile" asp-controller="Auth" asp-action="Logout" style="margin-left: 10px; font-family: 'Roboto', sans-serif; font-size: 18px;">
					<span>Logout</span>
				</a>
			}
			else
			{
				<i class="fa fa-user">
					<a class="icon icon-profile" asp-controller="Auth" asp-action="Login" style="margin-left: 10px; font-family: 'Roboto', sans-serif; font-size: 18px;">
						<span>Login</span>
					</a>
				</i>
			}
		</div>
	</div>
</header>

ECommerceCase.WebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - ECommerceCase.WebClient</title>
	
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	
	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="~/css/utils.css" />
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <style>
    	.w3-sidebar a {font-family: "Roboto", sans-serif}
    	body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: "Montserrat", sans-serif;}
    </style>
</head>

<body class="w3-content" style="max-width:1200px">
	@await Component.InvokeAsync("NavigationMenu")

	<div class="w3-main" style="margin-left:250px">
		@await Html.PartialAsync("_Header")

		@RenderBody()

		@await Html.PartialAsync("_Footer")
	</div>

	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>